Task 3 PR
biggerevil/Rails pull request #3
Opened 2021-01-11 13:48 UTC by biggerevil

Добавил инстанс-метод в user.rb,
Добавил метод класса в test.rb,
Создал миграцию и модель для пройденных тестов (user_passed_test),
Создал начальных данные в seeds.rb (и обновил development БД и schema.rb).

2021-01-11 18:42 UTC, VidgarVii requested changes

2021-01-11 18:42 UTC, VidgarVii commented on app/models/test.rb
> +  def self.sortedTestsNamesOfCategory(category_title)
в ruby в названиях метода и переменных принято использовать snake_case

2021-01-11 18:42 UTC, VidgarVii commented on app/models/test.rb
> +  end
надо бы определиться с кодом)
в order и where лучше использовать хеш
пример order(title: :desc)

2021-01-11 18:42 UTC, VidgarVii commented on app/models/user.rb
> +  def completedTestsOfLevel(level)
camelCase мы не используем!

2021-01-11 18:42 UTC, VidgarVii commented on app/models/user.rb
> +    titlesArray = Test.where(user_id: id, level: level).pluck(:title)
1 переменная не будет использована. Память загрязнять нет смысл
2 Создайте инстанс-метод в модели User, который принимает в качестве аргумента значение уровня сложности и возвращает **список всех Тестов, которые проходит или когда-либо проходил Пользователь на этом уровне сложности**

2021-01-11 18:42 UTC, VidgarVii commented on db/seeds.rb
> +firstUser = User.create({ nickname: 'lesserevil', mail: 'lesser@evil.com', password: 'WhichOneToChoose' })
лучше использовать `create!` - метод бросит исключение, если запись не создастся
сразу будет видно, если что-то пошло не так

2021-01-11 18:42 UTC, VidgarVii commented on db/seeds.rb
> +Test.create({ title: 'The very first test', level: 1, category_id: 1, user_id: 1 })
"хардкодить" `id` - не очень хорошая затея
такой "сид" невозможно накатить на существующую базу, ведь там id могут быть заняты другими записями или вовсе отсутствовать
правильней воспользоваться тем, что метод `create` возвращает созданные записи

2021-01-12 06:17 UTC, VidgarVii requested changes

2021-01-12 06:17 UTC, VidgarVii commented on app/models/user.rb
> +    Test.where(user_id: id, level: level)
Опять же не верно.
Создайте инстанс-метод в модели User, который принимает в качестве аргумента значение уровня сложности и возвращает список всех Тестов, которые проходит или **когда-либо проходил Пользователь** на этом уровне сложности

Разберись в методологии построении отношений таблиц. Какая связь за что отвечает.

2021-01-12 06:17 UTC, VidgarVii commented on db/seeds.rb
> +Answer.create!({ title: 'Lesser', correct: false, question_id: first_question.id })
еще метод create может принимать массив хешей

2021-01-12 08:17 UTC, biggerevil commented on app/models/user.rb
> +    Test.where(user_id: id, level: level)
Да, конечно, тут была ошибка
Используется не просто таблица Test, а сначала достаются id из UserPassedTest, а затем уже по этим id ищутся тесты в Test

2021-01-12 16:34 UTC, VidgarVii commented on app/models/user.rb
> +  end
Тут тоже будет правильно решить через джойн таблиц
то как ты делаешь - это "решение в лоб"
оно работает, но оно скажем мягко "не оптимальное"
рельсы многие запросы могут сами оптимизировать в итоге и, к примеру, составить автоматически из двух запросов один, но полагаться на это не стоит
в реальной жизни такие запросы, как у тебя получились, писать не нужно
плюс мы сейчас пытаемся разобраться с тем, как работают ассоциации в рельсах, чтобы в дальнейшем было понимание того "что же они делают" и "как это работает", так вот рельсы точно не пишут такие запросы, конечно же все оптимизировано.
здесь нужно в обоих методах решить все с помощью `joins` и `where` (в одно обращение к базе, один запрос)
пострайся разобраться - это важно и полезно

2021-01-12 19:38 UTC, merged